global:
  pipelineServiceClientConfig:
    apiEndpoint: http://openmetadata-dependencies-web.openmetadata.svc.cluster.local:8080
    metadataApiEndpoint: http://openmetadata.openmetadata.svc.cluster.local:8585/apii
